# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(837, 841)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.letterList = QtWidgets.QListView(self.centralwidget)
        self.letterList.setMinimumSize(QtCore.QSize(500, 0))
        self.letterList.setMaximumSize(QtCore.QSize(16777215, 30))
        self.letterList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.letterList.setFlow(QtWidgets.QListView.LeftToRight)
        self.letterList.setObjectName("letterList")
        self.horizontalLayout_2.addWidget(self.letterList)
        self.searchBox = QtWidgets.QLineEdit(self.centralwidget)
        self.searchBox.setObjectName("searchBox")
        self.horizontalLayout_2.addWidget(self.searchBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.artistList = QtWidgets.QListView(self.centralwidget)
        self.artistList.setMaximumSize(QtCore.QSize(250, 16777215))
        self.artistList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.artistList.setObjectName("artistList")
        self.horizontalLayout.addWidget(self.artistList)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabAlbums = QtWidgets.QWidget()
        self.tabAlbums.setObjectName("tabAlbums")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabAlbums)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.albumList = QtWidgets.QListView(self.tabAlbums)
        self.albumList.setObjectName("albumList")
        self.verticalLayout_3.addWidget(self.albumList)
        self.tabWidget.addTab(self.tabAlbums, "")
        self.tabBoots = QtWidgets.QWidget()
        self.tabBoots.setObjectName("tabBoots")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabBoots)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.bootList = QtWidgets.QListView(self.tabBoots)
        self.bootList.setObjectName("bootList")
        self.verticalLayout_4.addWidget(self.bootList)
        self.tabWidget.addTab(self.tabBoots, "")
        self.tabVideos = QtWidgets.QWidget()
        self.tabVideos.setObjectName("tabVideos")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tabVideos)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.videoList = QtWidgets.QListView(self.tabVideos)
        self.videoList.setObjectName("videoList")
        self.verticalLayout_5.addWidget(self.videoList)
        self.tabWidget.addTab(self.tabVideos, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.songList = QtWidgets.QListView(self.centralwidget)
        self.songList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.songList.setObjectName("songList")
        self.verticalLayout.addWidget(self.songList)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.fullscreenButton = QtWidgets.QCheckBox(self.centralwidget)
        self.fullscreenButton.setObjectName("fullscreenButton")
        self.horizontalLayout_3.addWidget(self.fullscreenButton)
        self.pauseButton = QtWidgets.QCheckBox(self.centralwidget)
        self.pauseButton.setObjectName("pauseButton")
        self.horizontalLayout_3.addWidget(self.pauseButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 837, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.letterList.clicked['QModelIndex'].connect(MainWindow.onLetterClick)
        self.artistList.clicked['QModelIndex'].connect(MainWindow.onArtistClick)
        self.songList.clicked['QModelIndex'].connect(MainWindow.onSongClick)
        self.albumList.clicked['QModelIndex'].connect(MainWindow.onAlbumClick)
        self.bootList.clicked['QModelIndex'].connect(MainWindow.onAlbumClick)
        self.videoList.clicked['QModelIndex'].connect(MainWindow.onAlbumClick)
        self.fullscreenButton.stateChanged['int'].connect(MainWindow.onFullscreen)
        self.pauseButton.stateChanged['int'].connect(MainWindow.onPause)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Laudable"))
        self.searchBox.setPlaceholderText(_translate("MainWindow", "Search"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAlbums), _translate("MainWindow", "Albums"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBoots), _translate("MainWindow", "Bootlegs"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabVideos), _translate("MainWindow", "Videos"))
        self.fullscreenButton.setText(_translate("MainWindow", "Fullscreen"))
        self.pauseButton.setText(_translate("MainWindow", "Pause"))

